name: Main Workflow

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - dev
      - main

jobs:
  qc:
    uses: ./.gitea/workflows/qc.yml
  
  test:
    needs: qc
    uses: ./.gitea/workflows/test.yml
