name: QC Stage

on:
    push:
        branches:
          - '**'
        tags:
          - 'v*'
    pull_request:
        branches:
          - 'main'
          - 'dev'

jobs:
    lint:
        name: Lint
        runs-on: ${{ vars.DEFAULT_RUNNER || 'ubuntu-latest' }}
        if: ${{ gitea.event_name != 'pull_request' || (gitea.base_ref != 'dev' && gitea.base_ref != 'main') }}
        continue-on-error: true
        container:
            image: node:${{ vars.NODE_VERSION || 'lts' }}-${{ vars.BASE_LAYER || 'slim' }}
        steps:
            - uses: actions/checkout@v4
            
            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run linting
              run: pnpm run lint

    lint-strict:
        name: Strict Linting
        runs-on: ${{ vars.DEFAULT_RUNNER || 'ubuntu-latest' }}
        if: ${{ gitea.event_name == 'pull_request' && (gitea.base_ref == 'dev' || gitea.base_ref == 'main') }}
        continue-on-error: false
        container:
            image: node:${{ vars.NODE_VERSION || 'lts' }}-${{ vars.BASE_LAYER || 'slim' }}
        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run strict linting
              run: pnpm run lint:strict

    check:
        name: Type Check
        runs-on: ${{ vars.DEFAULT_RUNNER || 'ubuntu-latest' }}
        container:
            image: node:${{ vars.NODE_VERSION || 'lts' }}-${{ vars.BASE_LAYER || 'slim' }}
        continue-on-error: ${{ gitea.event_name != 'pull_request' || (gitea.base_ref != 'dev' && gitea.base_ref != 'main') }}
        steps:
            - uses: actions/checkout@v4
            
            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run type check
              run: pnpm run check
