name: Project Tests
on:
    push:
        branches:
          - '**'
        tags:
          - 'v*'
    pull_request:
        branches:
          - 'main'
          - 'dev'

jobs:
    unit_tests:
        name: Unit Tests
        runs-on: ${{ vars.DEFAULT_RUNNER || 'ubuntu-latest' }}
        container:
            image: node:${{ vars.NODE_VERSION || 'lts' }}-${{ vars.BASE_LAYER || 'slim' }}
        continue-on-error: ${{ gitea.event_name != 'pull_request' || (gitea.base_ref != 'dev' && gitea.base_ref != 'main') }}
        steps:
          - uses: actions/checkout@v4

          - name: Install pnpm
            run: npm install --global pnpm@10.10.0

          - uses: actions/setup-node@v4
            with:
                node-version: 22
                cache: pnpm

          - name: Install dependencies
            run: pnpm clean-install

          - name: Run unit tests
            run: pnpm run test:unit
